//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h_admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comm
    {
        public int pkID { get; set; }
        public string Nam { get; set; }
        public string valuee { get; set; }
        public string dis { get; set; }
    }
}
